import { ArrowRight, Check, LoaderCircle, PartyPopper, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Seo } from "@/components/Seo";
import { trpc } from "@/lib/trpc";
import { assets } from "@/lib/visanam";

export default function Events() {
  const [form, setForm] = useState({ contactName: "", contactEmail: "", contactPhone: "", eventType: "Wedding", message: "" });
  const lead = trpc.leads.create.useMutation({ onSuccess: () => { toast.success("Your story idea is safely on its way to us."); setForm({ contactName: "", contactEmail: "", contactPhone: "", eventType: "Wedding", message: "" }); }, onError: () => toast.error("We could not send your message. Please try again.") });
  const submit = (event: FormEvent) => { event.preventDefault(); lead.mutate({ type: "event", schoolName: null, gradeRange: null, ...form }); };
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  return <><Seo title="Bespoke event comics" description="Turn a wedding, reception, celebration, or corporate milestone into a beautifully illustrated Visanam keepsake comic." />
    <section className="events-hero"><div className="events-art" style={{ backgroundImage: `url("${assets.meteorVillage}")` }} /><div className="container"><p className="section-kicker light"><PartyPopper size={14}/> Bespoke illustrated keepsakes</p><h1>Your greatest day,<br /><em>told like a story.</em></h1><p>We turn real people, real places, and big milestones into a comic world worth holding on to.</p></div></section>
    <section className="event-body container"><div className="event-intro"><div><p className="section-kicker">More than an invitation</p><h2>Give people a story<br /><em>they can step into.</em></h2></div><p>From wedding romances and receptions to joyful corporate milestones, Visanam’s production studio builds a tailor-made illustrated narrative with a distinctive visual language and a keepsake finish.</p></div><div className="event-offers"><article><span>01</span><h3>Weddings</h3><p>Your story, your in-jokes, your people — imagined as a comic to invite, delight, and keep.</p></article><article><span>02</span><h3>Receptions</h3><p>Make the welcome feel like the first page of an unforgettable night.</p></article><article><span>03</span><h3>Corporate events</h3><p>Turn a company milestone or client experience into a world worth talking about.</p></article></div><div className="b2b-form-grid event-form-grid"><div><p className="section-kicker">Tell us the beginning</p><h2>What kind of story are you celebrating?</h2><p>Share the shape of your occasion. We’ll respond with a thoughtful first approach to scope, style, and format.</p><ul><li><Check size={16}/> Bespoke art direction</li><li><Check size={16}/> Digital and print-ready formats</li><li><Check size={16}/> Character-led visual storytelling</li></ul></div><form className="lead-form" onSubmit={submit}><label>Your name<input value={form.contactName} onChange={(event) => update("contactName", event.target.value)} required /></label><div className="form-split"><label>Email<input type="email" value={form.contactEmail} onChange={(event) => update("contactEmail", event.target.value)} required /></label><label>Phone<input value={form.contactPhone} onChange={(event) => update("contactPhone", event.target.value)} required /></label></div><label>Event type<select value={form.eventType} onChange={(event) => update("eventType", event.target.value)}><option>Wedding</option><option>Reception</option><option>Corporate event</option><option>Other celebration</option></select></label><label>Tell us about the occasion<textarea value={form.message} onChange={(event) => update("message", event.target.value)} placeholder="Date, location, guests, the feeling you want to create…" required /></label><button className="button button-dark" disabled={lead.isPending}>{lead.isPending ? <><LoaderCircle className="spin" size={16}/> Sending…</> : <>Share your story idea <ArrowRight size={16}/></>}</button></form></div></section>
  </>;
}
