import { Seo } from "@/components/Seo";

const legal = {
  terms: { title:"Terms of use", intro:"These terms describe the respectful use of Visanam’s website, stories, and digital materials.", sections:[["Personal use", "Visanam Season 1 content is licensed for personal, household use by the purchaser. Please do not reproduce, distribute, resell, or publicly display the stories, artwork, prompts, or guides without written permission."],["No guarantees", "Visanam is an educational storytelling experience, not therapy, medical care, or a substitute for professional advice. Families should seek qualified support where it is needed."],["Intellectual property", "The Visanam name, story world, characters, illustrations, and parent materials are protected intellectual property. The public preview intentionally shares only a limited glimpse of the complete work."]] },
  privacy: { title:"Privacy notice", intro:"We aim to collect only what we need to make the Visanam experience work well for your family.", sections:[["Information you provide", "Purchase and inquiry forms collect the information shown in the form so we can process your order, shape your parent materials, or reply to your message."],["Children’s information", "Please provide only the child name and age information requested for your purchase. We do not ask children to create accounts or submit content through this website."],["Payments", "Payments are processed by Stripe. Card details are entered on Stripe’s secure checkout and are not stored by Visanam."],["Contact", "For a privacy request, contact the Visanam team through the relevant inquiry route on this site."]] },
  refund: { title:"Refund policy", intro:"We want families to feel confident about beginning their Visanam season.", sections:[["Digital access", "Because Season 1 includes digital story material and personalized parent guidance, please contact us promptly if you have a problem accessing or receiving your materials."],["How we help", "If a delivery issue or material error affects your experience, we will review the situation and offer an appropriate resolution. This may include replacement materials or, where suitable, a refund."],["Contact us", "Please include your purchase email and a brief description of the issue when you get in touch so we can help quickly."]] },
} as const;

export function Legal({ type }: { type: keyof typeof legal }) { const page = legal[type]; return <><Seo title={page.title} description={page.intro} /><section className="legal-page container"><p className="section-kicker">Visanam policies</p><h1>{page.title}</h1><p className="page-lede">{page.intro}</p><div>{page.sections.map(([title, copy]) => <article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</div></section></>; }
