import { Seo } from "@/components/Seo";

const legal = {
  terms: { title:"Terms of use", intro:"These terms describe the respectful use of Visanam’s website, stories, and digital materials.", sections:[["Personal use", "Visanam Season 1 content is licensed for personal, household use by the purchaser. Please do not reproduce, distribute, resell, or publicly display the stories, artwork, prompts, or guides without written permission."],["No guarantees", "Visanam is an educational storytelling experience, not therapy, medical care, or a substitute for professional advice. Families should seek qualified support where it is needed."],["Intellectual property", "The Visanam name, story world, characters, illustrations, and parent materials are protected intellectual property. The public preview intentionally shares only a limited glimpse of the complete work."]] },
  privacy: { title:"Privacy notice", intro:"We aim to collect only what we need to make the Visanam experience work well for your family.", sections:[["Information you provide", "Our waitlist and inquiry forms collect only what the form shows — an email address, an age range, and anything you choose to write to us — so we can tell you when Season 1 opens, shape your parent materials, or reply to your message."],["Children’s information", "We never create an account for your child, and we never ask for your child’s name, photograph, date of birth or school. To shape the parent guidance we ask only for an age range, such as 6–7 or 8–9. Children do not submit anything through this website, and we do not profile or advertise to them."],["Payments", "Season 1 is not yet on sale. When it opens, payments will be handled by a regulated payment provider on their own secure page. Visanam never sees or stores your card details."],["Contact", "For a privacy request, contact the Visanam team through the relevant inquiry route on this site."]] },
  refund: { title:"Refund policy", intro:"We want families to feel confident about beginning their Visanam season.", sections:[["Digital access", "Because Season 1 includes digital story material and personalized parent guidance, please contact us promptly if you have a problem accessing or receiving your materials."],["How we help", "If a delivery issue or material error affects your experience, we will review the situation and offer an appropriate resolution. This may include replacement materials or, where suitable, a refund."],["Contact us", "Please include your purchase email and a brief description of the issue when you get in touch so we can help quickly."]] },
} as const;

export function Legal({ type }: { type: keyof typeof legal }) { const page = legal[type]; return <><Seo title={page.title} description={page.intro} /><section className="legal-page container"><p className="section-kicker">Visanam policies</p><h1>{page.title}</h1><p className="page-lede">{page.intro}</p><div>{page.sections.map(([title, copy]) => <article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</div></section></>; }
