import { ArrowLeft, ArrowRight, Check, Download, Printer, Sparkles } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Seo } from "@/components/Seo";
import { assets, buildPlan, getPricingForTimezone, scenarios, ValueFocus, valueOptions } from "@/lib/visanam";

const ageBands = ["6–7 years", "8–9 years", "10–12 years"];

export default function ParentJourney() {
  const [step, setStep] = useState(() => Number(sessionStorage.getItem("visanam-journey-step")) || 1);
  const [ageBand, setAgeBand] = useState(() => sessionStorage.getItem("visanam-journey-age") || "");
  const [value, setValue] = useState<ValueFocus | "">(() => (valueOptions.some((item) => item.value === sessionStorage.getItem("visanam-journey-value")) ? sessionStorage.getItem("visanam-journey-value") as ValueFocus : ""));
  const [scenario, setScenario] = useState(() => sessionStorage.getItem("visanam-journey-scenario") || "");
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const tier = getPricingForTimezone(timezone);
  const plan = useMemo(() => value && scenario && ageBand ? buildPlan(value, scenario, ageBand) : null, [value, scenario, ageBand]);
  const selectedValueData = useMemo(() => value ? valueOptions.find((item) => item.value === value) : null, [value]);
  const suggestedMoments = selectedValueData?.moments ?? scenarios;
  const canAdvance = (step === 1 && ageBand) || (step === 2 && value) || (step === 3 && scenario);
  useEffect(() => { sessionStorage.setItem("visanam-journey-step", String(step)); sessionStorage.setItem("visanam-journey-age", ageBand); sessionStorage.setItem("visanam-journey-value", value); sessionStorage.setItem("visanam-journey-scenario", scenario); }, [step, ageBand, value, scenario]);
  const downloadPlan = () => {
    if (!plan || !value) return;
    const copy = `VISANAM · YOUR PARENT INSIGHT PLAN\n\n${plan.title}\n\nWHAT YOUR CHILD IS BUILDING\n${plan.outcome}\n${plan.whyItMatters}\n\nIN THE STORY\n${plan.childPractice}\n\n${plan.cue}\n\n${plan.ageNote}\n\nTonight’s three questions:\n${plan.questions.map((question, index) => `${index + 1}. ${question}`).join("\n")}\n\nYour Season 1 thread: Episodes ${plan.episodes.join(" + ")}.`;
    const url = URL.createObjectURL(new Blob([copy], { type: "text/plain" }));
    const link = document.createElement("a"); link.href = url; link.download = "visanam-parent-insight-plan.txt"; link.click(); URL.revokeObjectURL(url);
  };
  return <><Seo title="Parent Insight Journey" description="Choose a value and receive a gentle, story-led conversation plan to begin with your child tonight." />
    <section className="journey-shell"><div className="journey-top container"><Link href="/" className="small-back">← Home</Link><p className="section-kicker">The Parent Insight Journey</p><h1>A little clarity for the<br /><em>big feelings at home.</em></h1><p>There are no perfect answers here. Just a gentle place to begin.</p></div>
    <div className="journey-container container"><aside className="journey-progress" aria-label={`Step ${step} of 4`}>{["Your child", "Your focus", "A real moment", "Your plan"].map((label, index) => <div key={label} className={step >= index + 1 ? "done" : ""}><span>{step > index + 1 ? <Check size={13}/> : index + 1}</span><p>{label}</p></div>)}</aside>
      <section className="journey-card" id="printable-plan">
        <div className="journey-story-guide"><img src={assets.sprig} alt="" /><div><span>Sprig’s glow guide</span><p>Start with the moment your child knows. The story gives the skill a face, a feeling, and a gentle next step.</p></div><i aria-hidden="true" /></div>
        {step === 1 && <div className="journey-step"><p className="step-label">Step 1 of 4</p><h2>Who are we making room for?</h2><p className="journey-copy">For readers aged 6–12. Choose the age band that feels closest, and we’ll keep the language and conversation prompts comfortable for their stage.</p><div className="option-grid age-grid">{ageBands.map((age) => <button key={age} onClick={() => setAgeBand(age)} className={ageBand === age ? "selected" : ""}><span>{age}</span><small>{age === "6–7 years" ? "Early readers" : age === "8–9 years" ? "Growing storytellers" : "Big imaginations"}</small></button>)}</div></div>}
        {step === 2 && <div className="journey-step"><p className="step-label">Step 2 of 4</p><h2>What would you like your child to build?</h2><p className="journey-copy">Pick the inner skill that feels most useful in this chapter. Each one comes with a story practice and a familiar real-life moment.</p><div className="value-picker">{valueOptions.map((item) => <button key={item.value} onClick={() => setValue(item.value)} className={value === item.value ? "selected" : ""}><span style={{ background: item.glow }}></span><div><strong>{item.value}</strong><small>{item.outcome} · {item.childPractice}</small></div><Check size={17}/></button>)}</div></div>}
        {step === 3 && <div className="journey-step"><p className="step-label">Step 3 of 4</p><h2>Which {value ? value.toLowerCase() : "real-life"} moment feels familiar?</h2><p className="journey-copy">Choose the closest moment. This helps the story, questions, and next action meet your family where life is happening now.</p><div className="scenario-list">{suggestedMoments.map((item) => <button key={item} onClick={() => setScenario(item)} className={scenario === item ? "selected" : ""}><span>{scenario === item ? <Check size={16}/> : ""}</span>{item}</button>)}</div></div>}
        {step === 4 && plan && value && <div className="journey-step plan-result"><div className="plan-stamp"><Sparkles size={15}/> Your family’s gentle starting point</div><p className="step-label">Your Parent Insight Plan</p><h2>{plan.title}</h2><div className="plan-ritual-preview" aria-label="What your plan gives you tonight"><p>What you can use tonight</p><div><span>01</span><section><strong>A story doorway</strong><small>A scene that gives {value.toLowerCase()} a shape at a safe, imaginative distance.</small></section></div><div><span>02</span><section><strong>One familiar moment</strong><small>{scenario}</small></section></div><div><span>03</span><section><strong>A gentle next question</strong><small>{plan.questions[0]}</small></section></div></div><div className="growth-plan-card" style={{ borderColor: plan.glow }}><p>What your child is building</p><strong>{plan.outcome}</strong><span>{plan.whyItMatters}</span><b>In the story: {plan.childPractice}</b></div><p className="journey-copy">{plan.cue}</p><div className="plan-note" style={{ borderColor: plan.glow }}><strong>For your {ageBand} reader</strong><p>{plan.ageNote}</p></div><div className="question-card"><p>Three questions for tonight</p><ol>{plan.questions.map((question) => <li key={question}>{question}</li>)}</ol></div><div className="episode-thread"><span>YOUR SEASON 1 THREAD</span><strong>Episodes {plan.episodes.join(" + ")}</strong><p>These moments will give you a shared language for {value.toLowerCase()}—without turning the conversation into a lecture.</p></div><div className="plan-actions"><button className="button button-soft" onClick={downloadPlan}><Download size={16}/> Download plan</button><button className="button button-ghost" onClick={() => window.print()}><Printer size={16}/> Print it</button></div><Link href={`/checkout?value=${encodeURIComponent(value)}`} className="button button-dark plan-checkout">Join the Season 1 list <ArrowRight size={16}/></Link></div>}
        {step < 4 && <div className="journey-actions"><button className="button button-ghost" onClick={() => setStep(Math.max(1, step - 1))} disabled={step === 1}><ArrowLeft size={16}/> Back</button><button className="button button-dark" disabled={!canAdvance} onClick={() => setStep(step + 1)}>Continue <ArrowRight size={16}/></button></div>}
      </section></div></section>
  </>;
}
