import { ArrowRight, BookOpenCheck, Building2, Check, HeartHandshake, LoaderCircle } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Seo } from "@/components/Seo";
import { trpc } from "@/lib/trpc";
import { assets } from "@/lib/visanam";

export default function Schools() {
  const [form, setForm] = useState({ schoolName: "", contactName: "", contactEmail: "", contactPhone: "", gradeRange: "", message: "" });
  const lead = trpc.leads.create.useMutation({ onSuccess: () => { toast.success("Thank you — we’ll be in touch soon."); setForm({ schoolName: "", contactName: "", contactEmail: "", contactPhone: "", gradeRange: "", message: "" }); }, onError: () => toast.error("We could not send your message. Please try again.") });
  const submit = (event: FormEvent) => { event.preventDefault(); lead.mutate({ type: "school", ...form, eventType: null }); };
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  return <><Seo title="Schools and NEP SEL partnerships" description="Bring Visanam’s story-led Social and Emotional Learning experience to your school community." />
    <section className="b2b-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(17,48,51,.9),rgba(17,48,51,.28)),url("${assets.forestDay}")` }}><div className="container"><p className="section-kicker light">For schools and learning communities</p><h1>SEL that children don’t<br /><em>have to be told to love.</em></h1><p>A story-led Social and Emotional Learning experience that connects classroom reflection, home conversation, and the values your community cares about.</p></div></section>
    <section className="b2b-content container"><div className="b2b-intro"><div><p className="section-kicker">A shared language for growing up</p><h2>Bring the conversation<br /><em>into the living world.</em></h2></div><p>Visanam gives schools a welcoming way to support the social and emotional goals at the heart of India’s National Education Policy. Familiar characters and a continuing comic world make difficult themes easier to name, explore, and practise.</p></div><div className="benefit-grid"><article><BookOpenCheck size={24}/><h3>Story-led sessions</h3><p>Guided reflections rooted in episodes children genuinely want to discuss.</p></article><article><HeartHandshake size={24}/><h3>Family connection</h3><p>Parent conversation cards that continue the learning at home.</p></article><article><Building2 size={24}/><h3>Flexible implementation</h3><p>Designed for assemblies, advisory, life-skills periods, and class cohorts.</p></article></div><div className="b2b-form-grid"><div><p className="section-kicker">Start a conversation</p><h2>Could Visanam belong in your school?</h2><p>Tell us a little about your community. We’ll share an appropriate partnership approach and pilot options.</p><ul><li><Check size={16}/> Grade-appropriate discussion packs</li><li><Check size={16}/> Parent communication support</li><li><Check size={16}/> A launch path designed around your timetable</li></ul></div><form className="lead-form" onSubmit={submit}><label>School name<input value={form.schoolName} onChange={(event) => update("schoolName", event.target.value)} required /></label><div className="form-split"><label>Contact name<input value={form.contactName} onChange={(event) => update("contactName", event.target.value)} required /></label><label>Email<input type="email" value={form.contactEmail} onChange={(event) => update("contactEmail", event.target.value)} required /></label></div><div className="form-split"><label>Phone<input value={form.contactPhone} onChange={(event) => update("contactPhone", event.target.value)} required /></label><label>Grade range<input value={form.gradeRange} onChange={(event) => update("gradeRange", event.target.value)} placeholder="For example: Grades 3–6" required /></label></div><label>Message<textarea value={form.message} onChange={(event) => update("message", event.target.value)} placeholder="What would you like to explore?" required /></label><button className="button button-dark" disabled={lead.isPending}>{lead.isPending ? <><LoaderCircle className="spin" size={16}/> Sending…</> : <>Start the conversation <ArrowRight size={16}/></>}</button></form></div></section>
  </>;
}
