import React from "react";
import { ArrowRight, BookOpen, HeartHandshake, MessageCircleHeart, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { Reveal } from "@/components/Reveal";
import { Seo } from "@/components/Seo";

const chapters = [
  { number: "01", title: "The relationship", body: "A story creates a shared third place: it lets a child and parent look at a difficult feeling together, before asking either person to explain everything perfectly.", icon: HeartHandshake },
  { number: "02", title: "What happens in a story", body: "A familiar moment unfolds in Oru. A child sees a feeling, a choice, and a small repair at a safe, imaginative distance.", icon: BookOpen },
  { number: "03", title: "What happens after", body: "The story gives a family a simple language to return to: “What might be our next small step?”", icon: MessageCircleHeart },
];

export default function WhyVisanam() {
  return <><Seo title="Why Visanam matters for children and parents" description="Discover how Visanam uses stories to help families create a shared language for feelings, choices, connection, and small acts of repair." />
    <section className="why-hero abstract-why-hero"><div className="why-hero-geometry" aria-hidden="true"><i /><i /><span /></div><div className="container"><p className="section-kicker light"><Sparkles size={14} /> Why Visanam matters</p><h1>Not one more thing<br />to teach.<br /><em>A better way to be together.</em></h1><p>Children are meeting a louder, faster world. Visanam gives families an unhurried place to notice what matters, through stories that make room for feeling, choice, and connection.</p><Link href="/values" className="story-button story-button-light">Find a value to begin <ArrowRight size={17} /></Link></div></section>
    <section className="why-opening container"><Reveal><div className="why-opening-copy"><p className="section-kicker">A modern family ritual</p><h2>When life feels busy,<br /><em>connection needs a doorway.</em></h2><p>It is not always easy to begin with “How are you feeling?” A story can open the door differently. It makes a child’s experience visible without putting them on the spot, and gives a parent a gentle way in.</p></div></Reveal><Reveal delay={.1}><div className="why-opening-art" aria-label="An abstract glowing doorway"><span className="why-portal" aria-hidden="true" /><span>Every feeling is information.<br />None of it needs to be carried alone.</span></div></Reveal></section>
    <section className="why-trust" aria-label="What Visanam is and is not"><div className="container"><Reveal><div className="why-trust-intro"><p className="section-kicker">A clear promise to parents</p><h2>Stories for the moments<br /><em>you are already living.</em></h2></div></Reveal><div className="why-trust-grid"><Reveal delay={.04}><article><span>01</span><h3>Made for ages 6–12</h3><p>Gentle language and questions are shaped around a child’s stage, from little explorers to growing storytellers.</p></article></Reveal><Reveal delay={.1}><article><span>02</span><h3>A story, not a diagnosis</h3><p>Visanam offers imaginative practice and shared language. It does not promise a perfect answer or replace professional support when a family needs it.</p></article></Reveal><Reveal delay={.16}><article><span>03</span><h3>No scorecard at home</h3><p>There is no right response to perform. Begin with a real moment, stay curious together, and take one small next step.</p></article></Reveal></div></div></section>
    <section className="why-chapters"><div className="container"><Reveal><div className="why-section-head"><p className="section-kicker light">The Visanam way</p><h2>From a story moment<br /><em>to a family moment.</em></h2></div></Reveal><div className="why-chapter-grid">{chapters.map(({ number, title, body, icon: Icon }, index) => <Reveal key={title} delay={index * .08}><article><span className="why-chapter-number">{number}</span><Icon size={22} aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article></Reveal>)}</div></div></section>
    <section className="why-story-section container"><Reveal><div className="why-story-image" aria-label="An abstract illustration of a story unfolding"><span className="story-arch" /><span className="story-trail" /><i /><i /><i /></div></Reveal><Reveal delay={.08}><div className="why-story-copy"><p className="section-kicker">The story</p><h2>A child can meet<br /><em>themselves at a safer distance.</em></h2><p>Visanam stories do not hand children a rule. They make room for mistakes, pauses, listening, repair, and beginning again. That offers a vivid example without turning a hard moment into a lecture.</p><p className="why-pullquote">“The best conversations often begin after the page is closed.”</p><Link href="/oru" className="story-link">Step into Oru <ArrowRight size={17} /></Link></div></Reveal></section>
    <section className="why-journey"><div className="container"><Reveal><div className="why-journey-grid"><div><p className="section-kicker light">The journey</p><h2>One value.<br /><em>One shared next step.</em></h2></div><div><p>There is no scorecard and no perfect parent response. Families begin with the moment that feels most present, choose a value, and use the story as a small ritual they can return to.</p><ol><li><span>1</span> Choose the moment that feels close to home.</li><li><span>2</span> Read a story where that skill comes alive.</li><li><span>3</span> Carry one question into the week.</li></ol><Link href="/parents" className="story-button story-button-light">Create your gentle plan <ArrowRight size={17} /></Link></div></div></Reveal></div></section>
  </>;
}
